
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: s3_provider
    restart: always
    ports:
      - "${PORT}:5002"
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      gunicorn -c gunicorn.conf.py main:app
    networks:
      - boto_network



networks:
  boto_network:
    driver: bridge
